import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import {
  ResizableHandle,
  ResizablePanel,
  ResizablePanelGroup,
} from "@/frontend/components/ui/shadcn/resizable";
import {
  SidebarInset,
  SidebarProvider,
} from "@/frontend/components/ui/shadcn/sidebar";
import { Toaster } from "@/frontend/components/ui/shadcn/sonner";
import WorkflowLeftSidebar from "@/frontend/components/ui/workflow-interface/left-sidebar/LeftSidebar";
import WorkflowRightSidebar from "@/frontend/components/ui/workflow-interface/right-sidebar/RightSidebar";
import TopTabs from "@/frontend/components/ui/workflow-interface/top-tabs/TopTabs";
import type React from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Tensornode",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <head>
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased `}
      >
        <div className="w-[100svw] h-[100svh]">
          <SidebarProvider defaultOpen={true}>
            <ResizablePanelGroup direction="horizontal">
              <ResizablePanel minSize={15} defaultSize={15}>
                <WorkflowLeftSidebar />
              </ResizablePanel>
              <ResizableHandle />
              <ResizablePanel>
                <Toaster />
                <SidebarInset className="w-full h-full">
                  <TopTabs />
                  {children}
                </SidebarInset>
              </ResizablePanel>
              <ResizableHandle />
              <ResizablePanel minSize={15} defaultSize={15}>
                <WorkflowRightSidebar />
              </ResizablePanel>
            </ResizablePanelGroup>
          </SidebarProvider>
        </div>
      </body>
    </html>
  );
}
